# Generated by Django 3.1.7 on 2021-04-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
