# Generated by Django 3.1.7 on 2021-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210408_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
